# Site settings
title: UNDERWORLD
email: underworldfetnites@gmail.com
url: https://underworldfetishnights.com
description: "Needs more butts"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# give me dat font
assets:
   sources:
       -_assets/fonts

# Footer settings
footer: Underworld Fetish Nights

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/157254071627329/
  - title: instagram
    url: https://www.instagram.com/underworldfetish/
    
# Build settings
markdown: kramdown
permalink: pretty